# numpy is library 
it is collection of packages( which contains modlues)
means the numerical python
which is used in ml alogirthms, especially for data science




In [ ]:

import time
li=[3,5,6,32]
li
res1=[]
st=time.time()
for i in range:
    res1.append(i+5)
end=time.time()
print(res1)
print(end-st)
print(type(li))


[]
0.06716585159301758
<class 'list'>


In [18]:
import numpy as nd
import time
arr=nd.array([3,5,6,32])
res2=[]
st=time.time()
for i in range(1000000):
    # res2.append(i+5)
    pass
end=time.time()
print(end-st)

print(res2)
print(type(arr))

0.05045962333679199
[]
<class 'numpy.ndarray'>


In [ ]:
li=[3,5,6,32]# 1 dimensional array
import numpy as nd
arr=nd.array([3,5,6,32])# 3,4,6,7
res1=[]
# st=time.time()
print([i*2 for i in li])
# print(res1)
arr*2

[6, 10, 12, 64]


array([ 6, 10, 12, 64])

In [ ]:
#  two dimensional array
li=[3,5,6,32]# 1dimensional array
import numpy as nd
arr=nd.array([[3,5,6,32],[3,9,8,2]])# it contains two dimensional
print(type(arr))
print(arr)
# <class 'numpy.ndarray'>
# ndarray( 'n' dimensional array 'n' any number)




<class 'numpy.ndarray'>
[[ 3  5  6 32]
 [ 3  9  8  2]]


In [9]:
arr=nd.array([[3,5,6,32],[3,9,8,2]])# it contains two dimensional
print(id(arr))
# it supports the slicing like the list but does not create the new array
# it supports indexing also like the list 
# you can also give the values to the array dynamically


2235100108272


In [11]:
# creating the 3-d array
# you can also know the dimensions of by using the ndim()
one=nd.array([3,5,6,32])
two=nd.array([[3,5,6,32],[3,9,8,2]])
three=nd.array([[[3,5,6,32]],[[3,9,8,2]]])
print(nd.ndim(one))# it returns the  dimensions of specic array in numpy library
print(nd.ndim(two))

print(nd.ndim(three))


1
2
3


In [13]:
# you can also create the array with zeros initialy that you can specify the no of dimensions 
# you can know the no dimensions that your array but dont know the values that you want to add after
# you can do it with zeros method it takes the no of arguments for no rows,coulms
zero=nd.zeros(6) # 1D array with zeroes
print(zero)


[0. 0. 0. 0. 0. 0.]


In [ ]:
zero=nd.zeros(5,int)# array with zeroes 
# sytax:- zeroes(shape(for 2d,3d you can specify in tuple),datatype)
print(zero)



[0 0 0 0 0]


In [20]:
zero2=nd.zeros((3,3),dtype=int)

zero2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [31]:
ones=nd.ones(2,dtype=int)
ones2=nd.ones((3,5),dtype=int)

ones3=nd.ones((3,2,3),dtype=int)
print(ones)
# print(ones2)
print(ones3)



[1 1]
[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


In [ ]:
# if you want to crreate array with specific value that you want 
# using the full method
num=nd.full((3,4),5,int)            
num

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [37]:
# arrange for generating the values like the range function
h=nd.arange(10)
print(h)

[0 1 2 3 4 5 6 7 8 9]
